### ISSUE TITLE
Feature Request: CDN

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache#55]
@raamdev I'd like to request the following feature in QC Pro.
- I would like to be able to serve WordPress media from a CDN of my choosing. For instance, so I can cache static media at edge locations with CloudFront.

Here is a clip from a custom plugin that I've used for quite awhile now. Perhaps it could serve as a starting point for a whole new set of functionality that's offered by QC Pro when it comes to CDNs.

```
add_filter('pre_option_upload_path', 'cdn::uploads_path');
add_filter('pre_option_upload_url_path', 'cdn::uploads_url_path');

class cdn // Content delivery network for this site.
{
	public static function uploads_path()
		{
			return '/amazon-s3-bucket-mount';
			// Files uploaded through the WP Media Library go here.
		}

	public static function uploads_url_path()
		{
			return 'http://d1v41qemfjie0l.cloudfront.net/';
			// Files served by WordPress that reside in my `upload_path`; are served with this URL as the base.
		}
}
```

---

This code assumes that an S3 Bucket has been mounted locally, so it won't work unless a site owner can do that. Ideally, Quick Cache Pro could simplify this part further and make it easier for a novice site owner to set things up on their own.

---

### Other Considerations...

- It's probably worth having a discussion about how far QC Pro is going to take it's CDN integration — if and when it's added as a pro feature.

 The feature request here only asks for the Media Library. However, there are plugins like CloudFlare that deal with ALL static files served by WordPress, which is even better IMO.

- Which CDNs can we support? Some, or all of them? The code sample above could potentially work with any CDN that could be mounted locally. However, that's still problematic because not all of them can be of course.

- Multisite compatibility.

---

### A QC user recently wrote...

> I just installed your quick cache plugin last night and I just wanted to give you a quick suggestion that I think would improve sales significantly. I was looking at the difference in the free and pro versions and seeing if I wanted to upgrade, the thing that would have made me pay the $15 upgrade right away I didn\&#039;t see in the pro version. That feature is CDN image rewriting. The feature is present in both your top 2 competitors for free but your product is the easiest to use of the 3 products. I googled for the feature and found many people requesting the same feature from your product saying it\&#039;s the only thing that it\&#039;s missing. I also tried several other plugins along with your plugin to accomplish this feature and they wouldn\&#039;t point the images to my Amazon Cloudfront CDN properly while your plugin cached the pages. As a first time user that spent an hour analyzing solutions to speed up Wordpress last night I wanted to let you know that you would have
the perfect combination product if you added that one feature as caching and CDN are the top two methods to increase speed, why not make them into one super easy plugin? To keep things as simple as you have them all I would want is a single field to enter the new address to change the local image path into the CDN image path.

---

### TODOs

- [x] Create repo for AWS SDK. https://github.com/websharks/aws-php-sdk
- [x] Create repo for MaxCDN SDK. https://github.com/websharks/maxcdn-php-sdk
- [x] Add submodule for AWS SDK. `quick-cache-pro/submodules/aws-php-sdk`
- [x] Add submodule for MaxCDN SDK. `quick-cache-pro/submodules/maxcdn-php-sdk`
- [x] Rename `htmlc` submodule to `quick-cache-pro/submodules/html-compressor`
- [x] Initial URL filter-related methods implemented.
- [x] Implement content filtering methods; i.e. `content_filter()` in the `cdn_base` class.
- [x] Test MS Network compat. against `cdn_base::local_file()`.
- [ ] Work on `create_distro()` method for CloudFront.
- [ ] Work on `get_distro()` method for CloudFront.
- [ ] Work on `update_distro()` method for CloudFront.
- [ ] Work on `create_distro()` method for MaxCDN.
- [ ] Work on `get_distro()` method for MaxCDN.
- [ ] Work on `update_distro()` method for MaxCDN.
- [ ] Need to discuss cache invalidations again with @raamdev.

**Comment by ioerjfoige0439i** [comment]
@clavaque @raamdev @BruceCaldwell @jaswsinc @ethanpil @Reedyseth Don't forget about Amazon S3 and Amazon Cloudfront :-)!

**Comment by ioerjfoige0439i** [comment]
@clavaque @raamdev @BruceCaldwell @jaswsinc @ethanpil @Reedyseth As well as a “Generic” origin-pull Mirror in case we want to add other CDN's like CDN77 or CDN.net

**Comment by tokar86a** [comment]
How is it going? Any ETA?

**Comment by raamdev** [comment]
@tokar86a We'll have CDN functionality released as part of ZenCache, which is coming this month (the soft launch is likely happening this week).

If you're interested in testing a beta version when that goes out, please make sure you're on the [beta testers list](http://www.websharks-inc.com/r/quick-cache-beta-testers-list/).

**Comment by ethanpil** [comment]
Are we going to lose our registration when you switch over?

**Comment by raamdev** [comment]
> Are we going to lose our registration when you switch over?

No, you won't lose anything. All existing Quick Cache Pro customers will automatically have access to ZenCache Pro.

**Comment by ioerjfoige0439i** [comment]
Thanks guys, just signed up for the pro beta testers list

**Comment by tokar86a** [comment]
Hove is it going whit this soft release?

**Comment by raamdev** [comment]
@tokar86a The soft release is going well. :-) We should be doing a public release next week. I'll update here again when that happens.

**Comment by raamdev** [comment]
CDN Integration has been released as part of the changeover to ZenCache. 

See [Introduction to Static CDN Filters](http://zencache.com/kb-article/introduction-to-static-cdn-filters/).
